language: node_js
node_js:
- '8.6'
dist: trusty
jobs:
  include:
    - stage: test
      script: ./test 1
    - # stage name not required, will continue to use `test`
      script: ./test 1
    - stage: deploy
      script: ./test 1
# before_script:
# - npm list -g polymer-cli --depth=0 || npm install -g polymer-cli
# - npm list -g firebase-tools --depth=0 || npm install -g firebase-tools
# script:
# - cd $TRAVIS_BUILD_DIR/frontend
# - npm install
# - polymer build
# - cd $TRAVIS_BUILD_DIR/functions
# - npm install
# - npm run build
# - npm run lint
# after_success:
# - $TRAVIS_BUILD_DIR/.travis/deploy.sh develop
# cache:
#   directories:
#   - $(npm config get prefix)/bin/polymer-cli
#   - $(npm config get prefix)/bin/firebase-tools
#   - node_modules
notifications:
  email: false
  webhooks: https://travis.webhooks.m4m.io
